biotopedia_homepage:
    path:     /
    defaults: { _controller: BiotopediaCoreBundle:Accueil:index }

biotopedia_core_conditionsUtilisation:
    path:     /conditionsUtilisation
    defaults: { _controller: BiotopediaCoreBundle:Accueil:conditionsUtilisation }

############################################################################################

biotopedia_core_showImage:
    path:     /showImage/{id}
    defaults: { _controller: BiotopediaCoreBundle:Image:showImage }

############################################################################################

biotopedia_core_contact:
    path:     /contacts
    defaults: { _controller: BiotopediaCoreBundle:Contact:index }
