biotopedia_users:
    resource: "@BiotopediaUsersBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

########################################################################################
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
########################################################################################
biotopedia_core:
    resource: "@BiotopediaCoreBundle/Resources/config/routing.yml"
    prefix:   /
########################################################################################
biotopedia_users:
    resource: "@BiotopediaUsersBundle/Resources/config/routing.yml"
#########################################################################################
biotopedia_pisciotheque:
    resource: "@BiotopediaPisciothequeBundle/Resources/config/routing.yml"
#########################################################################################
biotopedia_mediatheque:
    resource: "@BiotopediaMediathequeBundle/Resources/config/routing.yml"
#########################################################################################