# app/config/security.yml
security:
    encoders:
        Biotopedia\UsersBundle\Entity\User:
            algorithm: sha512
            iterations: 8912
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        main:
            #id: bp_users.user_manager #Mon UserManager
            entity: { class: BiotopediaUsersBundle:User, property: username } #à decocher en cas d'utilisation sans usermanager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
            anonymous: true
            provider:  main
            logout:
                path: /logout
                target: /
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 jours en secondes

    access_control:
        - { path: ^/userAdmin*, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/deleteFamille, role: ROLE_ADMIN }
        - { path: ^/addCategorie, role: ROLE_ADMIN }
        - { path: ^/editCategorie, role: ROLE_ADMIN }
        - { path: ^/deleteCategorie, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }




#import du security.yml de mon UserBundle utilisant FOSUSERBundle -> à supprimer si j'arrive a fair mon propore UsersBundle
#imports:
    #- { resource: "@BiotopediaUserBundle/Resources/config/security.yml"}