<?php

namespace Biotopedia\MediathequeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{	
	//Récupère la totalité des catégories en B.D. et les classes par ordre alphabetique
	public function findAllOrderedByName()
	{
		//Récupère le QueryBuilder puis la Query corespondant à la selection et Result
		$qb = $this
			->createQueryBuilder('c')
			// Jointure sur l'attribut image
			->leftJoin('c.image', 'i')
			->addSelect('i')
			->orderBy('c.name', 'ASC');

    	return $qb->getQuery()->getResult();
	}

	public function countArticles()
	{
		//getSingleScalarResult permet de ne retourner qu'une seule valeur
    	return $this->createQueryBuilder('a')
    	->select('COUNT(a)')
    	->getQuery()->getSingleScalarResult();
	}
}
